# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1f0dee03f054874a79b33aeb2e784dbd096943af2233e5ac89b7768406c88177269fb3d642e0a0c06985d09d12a3ec215556e77f56b5696b9418767bcf9aec4

test:
  secret_key_base: 4de85bea6a8d0b9aa5597f9af936b4b841e3651881cea1cdd6ef5e8b8fcd84e3d30198c39ba01aed1da5e913b06043b27f934d0d69c9efb7dcc5090a5effe955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
